Task/controllers tests
shulyugin/thinknetica pull request #5
Opened 2017-03-09 20:21 UTC by shulyugin

PR for issue #4

2017-03-13 11:59 UTC, palkan requested changes

2017-03-13 11:59 UTC, palkan commented on app/controllers/answers_controller.rb
> +    @answer = @question.answers.create(answer_params)
Здесь нужно использовать `build`, сохранение у тебя ниже.

2017-03-13 11:59 UTC, palkan commented on app/controllers/answers_controller.rb
> +    @answers = @question.answers
Этот функционал должен быть в методе `questions#show`, мы хотим видеть ответы только на странице самого вопроса, `/questions/:id`.

2017-03-13 11:59 UTC, palkan commented on app/controllers/questions_controller.rb
> +    @question = Question.create(question_params)
`new`

2017-03-13 11:59 UTC, palkan commented on spec/controllers/answers_controller_spec.rb
> +    let(:answers) { create_list(:answer, 2, question: question) }
`create_list(:x, 2, ...) == create_pair(:x, ...)`

2017-03-13 11:59 UTC, palkan commented on spec/controllers/answers_controller_spec.rb
> +        expect { create_valid_answer }.to change(Answer, :count).by(1)
Здесь мы может использовать более специфичную проверку: `change(question.answers, :count)`. Так мы проверим, что ответ _привязан_ к нужному вопросу.

2017-03-13 12:46 UTC, shulyugin commented
@palkan, спасибо, исправил

2017-03-13 15:18 UTC, palkan commented on spec/controllers/answers_controller_spec.rb
> -  describe 'GET #index' do
Это нужно было не просто удалить, а перенести в `questions#show`, там у тебя будет загружаться вопрос с ответами

2017-03-18 11:42 UTC, merged

2017-03-18 11:42 UTC, shulyugin commented
@palkan, перенес в questions#show и вмержил