Acceptance tests
shulyugin/thinknetica pull request #7
Opened 2017-03-19 12:42 UTC by shulyugin

PR for #6

2017-03-22 14:19 UTC, palkan-th requested changes

2017-03-22 14:19 UTC, palkan-th commented on app/models/user.rb
> +  # Include default devise modules. Others available are:
`has_many :answers, ...`?

2017-03-22 14:19 UTC, palkan-th commented on app/controllers/questions_controller.rb
> +    if @question.user == current_user
Не нужно загружать объект пользователя для проверки, достаточно сравнить по id: `@question.user_id == current_user.id`.
Везде поправить.

2017-03-22 14:19 UTC, palkan-th commented on spec/controllers/answers_controller_spec.rb
>      describe 'DELETE #destroy' do
Нужны тесты, которые проверяют, что не-автор не может удалить (и для вопросов тоже).

2017-03-22 14:19 UTC, palkan-th commented on spec/features/answers/view_list_spec.rb
> +    page_answers = page.all('ul > li').map(&:text)
Очень сложно. Да и с привязкой к верстке – легко сломать в будущем.

Проще создавать ответы с уникальными текстами и проверять их наличие на странице.

Ну и проверку надо строить не от того, что на странице, а от того, что ты хочешь там увидеть.

2017-03-23 20:03 UTC, shulyugin commented
@palkan-th спасибо👍, замечания учел

2017-03-24 12:03 UTC, palkan-th approved these changes

2017-03-24 12:03 UTC, palkan-th commented on app/models/user.rb
> +  has_many :questions
`dependent`?

2017-03-24 17:35 UTC, merged

2017-03-24 17:36 UTC, shulyugin commented
@palkan-th, добавил dependent: :nullify